services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # volumes:
    #   - .:
    environment:
      - DATABASE_READ_URL=root:rootpassword@tcp(db-read:3307)/payment?charset=utf8mb4&parseTime=True&loc=Local
      - DATABASE_WRITE_URL=root:rootpassword@tcp(db-write:3306)/payment?charset=utf8mb4&parseTime=True&loc=Local
    networks:
      - app-network
    depends_on:
      - db-read
      - db-write
      - cache
  db-read:
    container_name: db-read
    image: mysql:8
    environment:
      - MYSQL_USER=readuser
      - MYSQL_PASSWORD=readpassword
      - MYSQL_DATABASE=payment
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3307:3306"
    volumes:
      - ./.mysql/mysql_data_read:/var/lib/mysql
    networks:
      - app-network
  db-write:
    container_name: db-write
    image: mysql:8
    environment:
      - MYSQL_USER=writeuser
      - MYSQL_PASSWORD=writepassword
      - MYSQL_DATABASE=payment
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql/mysql_data_write:/var/lib/mysql
    networks:
      - app-network
  cache:
    container_name: cache
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./:/src
volumes:
  db-read:
    driver: local
  db-write:
    driver: local
  cache:
    driver: local
networks:
  app-network:
    driver: bridge

